# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LayoutDeploymentChecklistItems < Formula
  desc ""
  homepage "https://github.com/pranaybinju/layout-deployment-checklist-items"
  version "0.2.6"

  on_macos do
    url "https://github.com/pranaybinju/layout-deployment-checklist-items/releases/download/v0.2.6/layout-deployment-checklist-items_0.2.6_darwin_all.tar.gz"
    sha256 "fe180bd572fb58f5f6595ea0a6712b976236a86dab7b671ae4190a95d1f58916"

    def install
      bin.install "layout-deployment-checklist-items"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pranaybinju/layout-deployment-checklist-items/releases/download/v0.2.6/layout-deployment-checklist-items_0.2.6_linux_amd64.tar.gz"
      sha256 "9675957aa7f33f0e39ab15cc75f7eb73ac30c0e342725e5c041f60cfee575259"

      def install
        bin.install "layout-deployment-checklist-items"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pranaybinju/layout-deployment-checklist-items/releases/download/v0.2.6/layout-deployment-checklist-items_0.2.6_linux_arm64.tar.gz"
      sha256 "ac5a73d32bc988d79e839540b863f7e0391441a5173270101136dc82de693291"

      def install
        bin.install "layout-deployment-checklist-items"
      end
    end
  end
end
